version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/dashboard
    ports:
      - 3000:3000
    image: dashboard:latest
    container_name: react_container
    command: npm start
